### ISSUE TITLE
W1PD159425 - eBooksMaker string index out of range exceptions - please fix ASAP

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#190]
genBook writing eBook: /Volumes/CTC/W1PD159425-སྡེ་སྤྲལ་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་གསུང་འབུམ།/W1PD159425-001.pdf
other exception during pdf generation: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.codePointAt(String.java:675)
  at org.tbrc.tools.ebooks.eBooksMaker.addFinalShad(eBooksMaker.java:159)
  at org.tbrc.tools.ebooks.eBooksMaker$XmlDocs.getAuthor(eBooksMaker.java:303)
  at org.tbrc.tools.ebooks.eBooksMaker.genBook(eBooksMaker.java:1524)
  at org.tbrc.tools.ebooks.eBooksMaker.generateBooks(eBooksMaker.java:1476)
  at org.tbrc.tools.ebooks.eBooksMaker.processRequest(eBooksMaker.java:1588)
  at org.tbrc.tools.ebooks.eBooksMaker.main(eBooksMaker.java:1777)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:483)
  at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
genBook writing eBook: /Volumes/CTC/W1PD159425-སྡེ་སྤྲལ་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་གསུང་འབུམ།/W1PD159425-002.pdf
other exception during pdf generation: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
…
genBook writing eBook: /Volumes/CTC/W1PD159425-སྡེ་སྤྲལ་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་གསུང་འབུམ།/W1PD159425-003.pdf
other exception during pdf generation: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
…
genBook writing eBook: /Volumes/CTC/W1PD159425-སྡེ་སྤྲལ་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་གསུང་འབུམ།/W1PD159425-004.pdf
other exception during pdf generation: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
…

**Comment by TBRC-Travis** [comment]
Chris provided a fix with the release of eBooksMaker-1.4.43.jar. This has been resolved.
