### ISSUE TITLE
W1KG6113 - eBooksMaker exception thrown during DLD ebook generation

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#201]
Looks like something funky with the title of the work.  Here's the error output:

```
byName__ fetched W1KG6113 in collection /db/tbrc/tbrc-works
XmlDocs calling getOutlineForWork(W1KG6113)
doQuery running get-outline-by-work-rid:get-outline-by-work-rid("W1KG6113") 
With generated query:
import module namespace qNS="http://tbrc.org/exist/xquery/get-outline-by-work-rid"
	at "xmldb:exist:///db/modules/gwt/get-outline-by-work-rid.xqm";

let $doc := qNS:get-outline-by-work-rid("W1KG6113")
return $doc
Outputting Table of Contents: /Volumes/DLD/batch2/W1KG6113-lokesh chandra/_batch 1/W1KG6113-000-དཀར་ཆག་-lokesh chandra/_batch 1.pdf
java.lang.Exception: Error: Couldn't open PDF file '/Volumes/DLD/batch2/W1KG6113-lokesh chandra/_batch 1/W1KG6113-000-དཀར་ཆག་-lokesh chandra/_batch 1.pdf' for writing (no such directory)
	at org.tbrc.tools.ebooks.eBooksMaker.generateToC(eBooksMaker.java:1387)
	at org.tbrc.tools.ebooks.eBooksMaker.processRequest(eBooksMaker.java:1584)
	at org.tbrc.tools.ebooks.eBooksMaker.main(eBooksMaker.java:1777)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Error: Couldn't open PDF file '/Volumes/DLD/batch2/W1KG6113-lokesh chandra/_batch 1/W1KG6113-000-དཀར་ཆག་-lokesh chandra/_batch 1.pdf' for writing (no such directory)
genBook writing eBook: /Volumes/DLD/batch2/W1KG6113-lokesh chandra/_batch 1/W1KG6113-001.pdf
writeCover title english lokesh chandra/_batch 1
writeCover author tibetan ལོཀེཤ་ཆནདྲ་
writeCover title english lokesh chandra/_batch 1

```

**Comment by xristy** [comment]
There's a slash, "/", in the title and the title is marked as english and so the slash is slipping through as part of the path for the pdf which now includes a nonexistent dir, "_batch 1".

Solution is to fix the title

**Comment by TBRC-Travis** [comment]
Thanks Chris.  I'll assign to @karmagongde to fix the title.

**Comment by karmagongde** [comment]
removed slash from title.

**Comment by TBRC-Travis** [comment]
Thanks Karma!
