### ISSUE TITLE
W2PD19353 - eBooksMaker PDFlibException thrown during DLD ebook generation

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#202]
This work is an example of about a dozen works that fail during eBook generation with an error stating _"com.pdflib.PDFlibException: Font 'Chinese' with encoding 'unicode': Couldn't open font file '华文细黑.ttf' for reading (no such regular file)"_.

Here's the full error output:

```
doQuery running get-outline-by-work-rid:get-outline-by-work-rid("W2PD19353") 
With generated query:
import module namespace qNS="http://tbrc.org/exist/xquery/get-outline-by-work-rid"
	at "xmldb:exist:///db/modules/gwt/get-outline-by-work-rid.xqm";

let $doc := qNS:get-outline-by-work-rid("W2PD19353")
return $doc
Outputting Table of Contents: /Volumes/NT_Travis/2018_DLD/batch3/W2PD19353-佛教故事选
/W2PD19353-000-དཀར་ཆག་-佛教故事选
.pdf
writeCover title chinese 佛教故事选

writeCover page: 1 writing title textblock got error: Font 'Chinese' with encoding 'unicode': Couldn't open font file '华文细黑.ttf' for reading (no such regular file)
writeCover title chinese 佛教故事选

writeCover page: 2 writing title textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing karchag in volume textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing cover imageblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing license_bo textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing license_zh textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing license textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing access_bo textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing access_zh textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing access textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing timestamp textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
writeCover page: 2 writing generator textblock got error: Missing or invalid Block format version (file '/Users/tbrc/staging/eBooks/front-matter/cover-template-C04-A4-with-blocks.pdf', page 2)
addHeading chinese 佛教故事选

PDFlib exception occurred in eBooksMaker:
[1016] add_textflow: Font 'Chinese' with encoding 'unicode': Couldn't open font file '华文细黑.ttf' for reading (no such regular file)
PDFlib exception occurred in eBooksMaker:
com.pdflib.PDFlibException: Font 'Chinese' with encoding 'unicode': Couldn't open font file '华文细黑.ttf' for reading (no such regular file)
	at com.pdflib.pdflib.PDF_add_textflow(Native Method)
	at com.pdflib.pdflib.add_textflow(pdflib.java:190)
	at org.tbrc.tools.ebooks.eBooksMaker.addHeading(eBooksMaker.java:624)
	at org.tbrc.tools.ebooks.eBooksMaker.walkOutline(eBooksMaker.java:1075)
	at org.tbrc.tools.ebooks.eBooksMaker.generateToC(eBooksMaker.java:1411)
	at org.tbrc.tools.ebooks.eBooksMaker.processRequest(eBooksMaker.java:1584)
	at org.tbrc.tools.ebooks.eBooksMaker.main(eBooksMaker.java:1777)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
genBook writing eBook: /Volumes/NT_Travis/2018_DLD/batch3/W2PD19353-佛教故事选
/W2PD19353-001.pdf
writeCover title chinese 佛教故事选

writeCover page: 1 writing title textblock got error: Font 'Chinese' with encoding 'unicode': Couldn't open font file '华文细黑.ttf' for reading (no such regular file)
writeCover title chinese 佛教故事选

```

**Comment by xristy** [comment]
Looks like the chinese font file isn't present. Environment var needs fixing?

**Comment by TBRC-Travis** [comment]
I'll need to know the proper font file to use and where to obtain it.  At the moment there are no Chinese fonts present in our eBooks font collection.

**Comment by xristy** [comment]
The font name is in the error:  华文细黑.ttf. 

Googling seems to return some useful hits. Someone in the office like Dechen or Chungdak may know a better font. That font name, 华文细黑.ttf, is evidently in an environment var - it's not in the program.

**Comment by TBRC-Travis** [comment]
Thanks Chris.  This is fixed now.  I downloaded the Chinese font file and pointed eBooksMaker to the appropriate fonts dir.  The PDF is now being generated with the correct Chinese title.
